services:
  - type: web
    name: hojavida-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hojavida_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DATABASE_URL
        fromDatabase:
          name: hojavida-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: hojavida-db
    plan: free # El plan gratuito de Render